apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-config-volume
              mountPath: /etc/mysql/conf.d/custom.cnf
              subPath: custom.cnf
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "400Mi"
              cpu: "300m"
      volumes:
        - name: mysql-config-volume
          configMap:
            name: mysql-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
